// theme.jsx — color palettes for the pre-triage app

const THEMES = {
  warm: {
    name: 'Warm',
    bg: '#f5efe2',           // cream
    surface: '#fbf6ec',
    surfaceAlt: '#efe7d4',
    border: '#e3dac3',
    ink: '#2b2a26',
    inkSoft: '#6b675c',
    inkMuted: '#8e8a7d',
    accent: '#5b7a63',       // sage
    accentInk: '#23362a',
    accentSoft: '#dfe7d9',
    badge: '#3d5a45',
    statusGreen: '#5b7a63',
    statusAmber: '#c98a3a',
    statusRed: '#b3493a',
    statusBlue: '#4a6f8a',
    chrome: 'light',
    fontDisplay: '"Fraunces", Georgia, serif',
    fontBody: '"Inter", system-ui, sans-serif',
    fontMono: '"JetBrains Mono", ui-monospace, monospace',
    bodySize: 17,
  },
  calm: {
    name: 'Calm clinical',
    bg: '#eef3f6',
    surface: '#ffffff',
    surfaceAlt: '#e8eef3',
    border: '#d6dee5',
    ink: '#0f1e2a',
    inkSoft: '#4b5d6d',
    inkMuted: '#7c8a98',
    accent: '#2f6fb0',
    accentInk: '#0c2c47',
    accentSoft: '#dde8f3',
    badge: '#1f4f80',
    statusGreen: '#2e7a55',
    statusAmber: '#b27a2a',
    statusRed: '#a83b32',
    statusBlue: '#2f6fb0',
    chrome: 'light',
    fontDisplay: '"Inter", system-ui, sans-serif',
    fontBody: '"Inter", system-ui, sans-serif',
    fontMono: '"JetBrains Mono", ui-monospace, monospace',
    bodySize: 17,
  },
  bold: {
    name: 'Bold dark',
    bg: '#0e1311',
    surface: '#171c1a',
    surfaceAlt: '#1f2624',
    border: '#2c3431',
    ink: '#f1efe7',
    inkSoft: '#b6b2a5',
    inkMuted: '#8a877c',
    accent: '#a3d9b1',
    accentInk: '#0e1311',
    accentSoft: '#1d2a23',
    badge: '#a3d9b1',
    statusGreen: '#7fc794',
    statusAmber: '#e0a85a',
    statusRed: '#e07565',
    statusBlue: '#7fb1d9',
    chrome: 'dark',
    fontDisplay: '"Fraunces", Georgia, serif',
    fontBody: '"Inter", system-ui, sans-serif',
    fontMono: '"JetBrains Mono", ui-monospace, monospace',
    bodySize: 17,
  },
  accessible: {
    name: 'Accessible',
    bg: '#ffffff',
    surface: '#ffffff',
    surfaceAlt: '#f0f0f0',
    border: '#000000',
    ink: '#000000',
    inkSoft: '#1a1a1a',
    inkMuted: '#3a3a3a',
    accent: '#005a9e',
    accentInk: '#ffffff',
    accentSoft: '#e6f0fa',
    badge: '#003e6e',
    statusGreen: '#0a6b35',
    statusAmber: '#8a4b00',
    statusRed: '#9b1a1a',
    statusBlue: '#003e6e',
    chrome: 'light',
    fontDisplay: '"Inter", system-ui, sans-serif',
    fontBody: '"Inter", system-ui, sans-serif',
    fontMono: '"JetBrains Mono", ui-monospace, monospace',
    bodySize: 20,
  },
};

window.THEMES = THEMES;
